model:
  embedding_dim: 512
  n_filters: 100
  filter_sizes:
    - 3
    - 4
    - 5
  output_dim: 3
  dropout: 0.3
  max_sent_len: 120
  checkpoint_path: model_checkpoint/cnn.pth.tar

train:
  learning_rate: 0.005
  num_epochs: 10
  